# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e258432eac8a574e96c298ee5a198c5d25a8a02be18656be2998de84bf412a49779ab9fdf876fdca7164f3b54422cc8cd044cfc13d5261f589dfa5489198fd2

test:
  secret_key_base: 781a392f046ce32fc694de6bb26ed7aae425110d0a84635fc1ff7343562ee01878c282779ab671a15f798f014891d79d22e392f8e1c9e053277090e7415e7c0e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
